AllCops:
  Exclude:
    - 'db/schema.rb' # generated file
    - 'vendor/**/*' # need for travis-ci
    # http://caseywest.com/faster-ci-on-travis-and-docker-for-ruby-and-rails-and-rubocop/

Style/EndOfLine:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/BlockComments:
  Enabled: false

Metrics/AbcSize:
  Max: 29

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'app.rb'
