Style/EndOfLine:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Style/BlockComments:
  Enabled: false

Metrics/AbcSize:
  Max: 23

Style/RescueModifier:
  Enabled: false

Metrics/LineLength:
  Max: 90
